apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name:  bootstrap.gitops.metis.platform.crossplane.io
  labels:
    provider: kubernetes
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: gitops.metis.platform.crossplane.io/v1alpha1
    kind: Bootstrap
  resources:
    - base:
        apiVersion: tools.metis.platform.crossplane.io/v1alpha1
        kind: ArgoCD
        metadata:
          name: argocd-metis
        spec:
          id: argocd-metis
      patches:        # All Helm releases derive the ProviderConfig to use from the XR.
        - fromFieldPath: spec.providerHelmConfigRef.name
          toFieldPath: spec.providerHelmConfigRef.name
    - base:
        apiVersion: gitops.metis.platform.crossplane.io/v1alpha1
        kind: AppSetModule
        metadata:
          name: apset-logging
        spec:
          revision: main
          path: charts-modules/*
          repoURL: https://github.com/bbdsoftware/metis-cluster-bootstraps.git
          aws:
            enabled: "true"
            iamServiceAccounts:
              enab  led: "true"
              iamRoleArn: NOTPROVIDED
      patches:        # All Helm releases derive the ProviderConfig to use from the XR.
        - fromFieldPath: spec.providerKubernetesConfigRef.name
          toFieldPath: spec.providerKubernetesConfigRef.name