apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: bootstraps.gitops.metis.platform.crossplane.io
spec:
  group: gitops.metis.platform.crossplane.io
  names:
    kind: Bootstrap
    plural: bootstraps
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: "git tag  branch  commit"
              providerHelmConfigRef:
                type: object
                description: "A reference to the helm ProviderConfig of the cluster that services should
                            be deployed to."
                properties:
                  name:
                    type: string
                    description: "Name of the Kubernetes provider configuration.
                                  This will typically be the name of the cluster with a
                                  five character suffix appended."
                required:
                  - name
              providerKubernetesConfigRef:
                type: object
                description: "A reference to the kubernetes ProviderConfig of the cluster that services should
                                          be deployed to."
                properties:
                  name:
                    type: string
                    description: "Name of the Kubernetes provider configuration.
                                                This will typically be the name of the cluster with a
                                                five character suffix appended."
                required:
                  - name
            required:
                - providerHelmConfigRef
                - providerKubernetesConfigRef
                - name