apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: argocds.tools.metis.platform.crossplane.io
spec:
  group: tools.metis.platform.crossplane.io
  names:
    kind: ArgoCD
    plural: argocds
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: Name of the argo rleaset.
